name: "adguard-sync"
services:
  adguard-sync:
    depends_on:
      adguard-master:
        condition: "service_healthy"
        restart: true
      adguard-slave:
        condition: "service_healthy"
        restart: true
    image: "11notes/adguard-sync:0.7.8"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "adguard-sync.etc:/adguard-sync/etc"
    ports:
      - "3000:3000/tcp"
    networks:
      frontend:
    restart: "always"

  adguard-master:
    image: "11notes/adguard:0.107.63"
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
      - "3001:3000/tcp"
    networks:
      frontend:
    restart: "always"

  adguard-slave:
    image: "11notes/adguard:0.107.63"
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "2053:53/udp"
      - "2053:53/tcp"
      - "3002:3000/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
 adguard-sync.etc:

networks:
  frontend: