cron: "*/10 * * * *"
runOnStart: true
continueOnError: true

origin:
  url: https://192.168.1.2:3000
  insecureSkipVerify: false
  username: username
  password: password

replicas:
  - url: http://192.168.1.3
    username: username
    password: password
  - url: http://192.168.1.4
    username: username
    password: password

api:
  port: 8080
  username: admin
  password: adguard
  darkMode: true

features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true