cron: "*/15 * * * *"
runOnStart: true
continueOnError: false

origin:
  url: https://adguard-master:8443
  insecureSkipVerify: true
  username: admin
  password: adguard

replicas:
  - url: https://adguard-slave:8443
    insecureSkipVerify: true
    username: admin
    password: adguard

api:
  port: 8443
  username: admin
  password: adguard
  darkMode: true
  tls:
    certDir: /adguard-sync/etc/ssl
    certName: default.crt
    keyName: default.key

features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true