cron: "*/15 * * * *"
runOnStart: true
continueOnError: false

origin:
  url: http://adguard-master:3000
  username: admin
  password: adguard

replicas:
  - url: http://adguard-slave:3000
    username: admin
    password: adguard

api:
  port: 3000
  username: admin
  password: adguard
  darkMode: true
  metrics:
    enabled: true
    scrapeInterval: 10s
    queryLogLimit: 10000

features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true